// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP1CV74KcNtKb0nryrOPp2y8wthPYNY9g',
    appId: '1:402361119151:web:5bd5ade8b39e3ad8297f5a',
    messagingSenderId: '402361119151',
    projectId: 'trn-project1',
    authDomain: 'trn-project1.firebaseapp.com',
    storageBucket: 'trn-project1.appspot.com',
    measurementId: 'G-33VEFC45PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9UW-23eQez9J0Erfnjo2_xfRtxVO8ft4',
    appId: '1:402361119151:android:fe610700a463793b297f5a',
    messagingSenderId: '402361119151',
    projectId: 'trn-project1',
    storageBucket: 'trn-project1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMy2OaVhmUjJDCAdsqbyaGexFoeNdFThM',
    appId: '1:402361119151:ios:32da3a46528bb84a297f5a',
    messagingSenderId: '402361119151',
    projectId: 'trn-project1',
    storageBucket: 'trn-project1.appspot.com',
    iosClientId:
        '402361119151-rfftv1nva0avdkpd7ioibnn6duk0r6ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.trnProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMy2OaVhmUjJDCAdsqbyaGexFoeNdFThM',
    appId: '1:402361119151:ios:262fd05e15b73a1c297f5a',
    messagingSenderId: '402361119151',
    projectId: 'trn-project1',
    storageBucket: 'trn-project1.appspot.com',
    iosClientId:
        '402361119151-rsc8o5gnu2k0ijdc5tjqivlaf9081c8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.trnProject2.RunnerTests',
  );
}
